name       : libarcus
version    : 3.1.0
release    : 6
source     :
    - https://github.com/Ultimaker/libArcus/archive/3.1.0.tar.gz : 1ce0fc0e979a8d43923727f45408b98fd9d77a520a880fe8a07a33a438fafa50
license    : LGPL-3.0
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating
    a socket in a thread and using this socket to send and receive messages
    based on the Protocol Buffers library. It is designed to facilitate the
    communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python3-sip-devel
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
