name       : libarcus
version    : 4.11.0
release    : 32
source     :
    - https://github.com/Ultimaker/libArcus/archive/4.11.0.tar.gz : 2682a898a033f855c9a9d24da976a5467f8823b448db86e308d54017c0c6a372
homepage   : https://github.com/Ultimaker/libArcus
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating a socket in a thread and using this socket to send and receive messages based on the Protocol Buffers library. It is designed to facilitate the communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-sip-4
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
