name       : libarcus
version    : 2.7.0
release    : 1
source     :
    - https://github.com/Ultimaker/libArcus/archive/2.7.0.tar.gz : 18905c627291858ec97f69b2e730d8ce847dd76813150fa6658aaece2d1485fb
license    : LGPL-3.0
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating
    a socket in a thread and using this socket to send and receive messages
    based on the Protocol Buffers library. It is designed to facilitate the
    communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python-3.5)
    - python3-sip-devel
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
