name       : libarcus
version    : 4.13.1
release    : 37
source     :
    - https://github.com/Ultimaker/libArcus/archive/refs/tags/4.13.1.tar.gz : 51e865cb648750ad9ea315fa7632ee7016890273f911270f60d28c8a4bc50240
homepage   : https://github.com/Ultimaker/libArcus
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating a socket in a thread and using this socket to send and receive messages based on the Protocol Buffers library. It is designed to facilitate the communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-sip-4
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-protobuf-deprecated.patch
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
