name       : libarcus
version    : 4.9.1
release    : 26
source     :
    - https://github.com/Ultimaker/libArcus/archive/4.9.1.tar.gz : 18d939fd2428c72fdce35a286c196438327cfc3c8476e463e5ca46570168c9ce
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating a socket in a thread and using this socket to send and receive messages based on the Protocol Buffers library. It is designed to facilitate the communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python3-sip-devel
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
