name       : libarcus
version    : 4.6.1
release    : 21
source     :
    - https://github.com/Ultimaker/libArcus/archive/4.6.1.tar.gz : 8e8a128b6e0049e583761b5ba5980babd5a37f39e363e502736196c094919513
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating a socket in a thread and using this socket to send and receive messages based on the Protocol Buffers library. It is designed to facilitate the communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python3-sip-devel
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
