name       : libarcus
version    : 3.0.3
release    : 2
source     :
    - https://github.com/Ultimaker/libArcus/archive/3.0.3.tar.gz : 278a0f7f5b445e6e396f28488055488be1cf56fa325b1766ca94fe9737ffa189
license    : LGPL-3.0
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating
    a socket in a thread and using this socket to send and receive messages
    based on the Protocol Buffers library. It is designed to facilitate the
    communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python-3.5)
    - python3-sip-devel
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
