name       : libarcus
version    : 4.10.0
release    : 29
source     :
    - https://github.com/Ultimaker/libArcus/archive/4.10.0.tar.gz : 04a9eb24ad5a55ffb24888c2dc83b6486d704536f457bce0e6c5523cd6cadae8
homepage   : https://github.com/Ultimaker/libArcus
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Communication library between internal components for Ultimaker software
description: |
    This library contains C++ code and Python3 bindings for creating a socket in a thread and using this socket to send and receive messages based on the Protocol Buffers library. It is designed to facilitate the communication between Cura and its backend and similar code.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-sip-4
setup      : |
    %cmake . -DBUILD_EXAMPLES=OFF
build      : |
    %make
install    : |
    %make_install
